services:
    redis:
        container_name: redis_performance
        image: redis
        restart: always
        ports:
            - 6379:6379
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    mongo:
        container_name: mongo_performance
        image: mongo
        restart: always
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=31Kp9T3Z!Hs+R=ma

    mysql:
        container_name: mysql_performance
        image: mysql
        restart: always
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=vKq^1#*86zBp=5Z[
            - MYSQL_DATABASE=performance
            - MYSQL_USER=user_performance
            - MYSQL_PASSWORD=pa9^J#s9NOqmGv3C